<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Untitled</title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">

<link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
<table class="main">
	<tr>	
	  <td class="main">
	  	<table class="main2">
			<tr>
				<td class="top">
					<table>
						<tr>
							<td class="top1">
								<table>
									<tr>
										<td class="top1_left">
											  <div>www.iluna.co.jp</div>
										</td>
										<td class="top1_right">
											<div class="img">
											<img alt="" src="img/p1.gif"><img alt="" src="img/p2.gif"><img alt="" src="img/p3.gif"><img alt="" src="img/p4.gif"><img alt="" src="img/p5.gif">
											</div>
											<div id="menu">
												<ul>
												<li id="menu01"><a href="index.html">HOME</a></li>
												<li id="menu02"><a href="service.html">サービス</a></li>
												<li id="menu03"><a href="about.html">iLUNAとは</a></li>
												<li id="menu04"><a href="alliance.html">アライアン</a></li>
												<li id="menu05"><a href="contact.html">お問い合わせ</a></li>
												</ul>
											</div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td class="top2">
								<table>
									<tr>
										<td class="bg"></td>
										<td class="top2_left">
								<div id="title_left">
								<img alt="" src="img/1_z1.gif">ニュース
								</div>
								<div id="line"><img alt="" src="img/1_line1.gif"></div>
								<div id="index_red"><strong>2008年8月8日</strong></div>
								<div id="index_contents72">大人のブラックテイストマガジンLUSSWに代表 矢作が紹介されました
</div>
<div id="line"><img alt="" src="img/1_line2.gif"></div>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class="bottom">
					<table>
						<tr>
							<td class="bg"></td>
							<td class="bottom_left">
								<div id="index_red"><strong>2008年8月9日</strong></div>
								<div id="index_contents72"><a href="http://www.tenmono.com/blog_parts/">年収・給料・給与を上場企業から計る「転職のモノサシ」のブログパーツをリリースしました</a>
</div>
<div id="line"><img alt="" src="img/1_line2.gif"></div>
								<div id="index_red"><strong>2008年8月8日</strong></div>
								<div id="index_contents72"><a href="http://www.tenmono.com/">年収・給料・給与を上場企業から計る「転職のモノサシ」をオープンしました</a>
</div>
<div id="line"><img alt="" src="img/1_line2.gif"></div>
								<div id="index_red"><strong>2008年8月6日</strong></div>
								<div id="index_contents72"><a href="http://www.iluna.co.jp/">株式会社イルナコーポレートサイトをオープンしました</a>
</div>
<div id="line"><img alt="" src="img/1_line2.gif"></div>

							</td>
							<td class="bottom_bg"></td>
							<td class="bottom_right1">
								<div id="title_right"><img alt="" src="img/1_z3.gif">会社概要</div>
								<div style="margin-left:21px; margin-top:10px "><img alt="" src="img/1_line3.gif"></div>
							  <div id="index_yellow"><strong>社名</strong></div>
							  <div id="index_contents">株式会社イルナ( iLUNA, Inc. )</div>
							  <div id="index_yellow"><strong>事業内容</strong></div>
							  <div id="index_contents">インターネットを使ったビジネスの企画・開発・運営</div>
							  <div id="index_yellow"><strong>連絡先</strong></div>
							  <div id="index_contents">電話: 03-5436-6508（代表）</div>
							  <div id="index_contents">FAX: 03-5436-0860</div>
							  <div id="index_contents">Eメール：<a href="mailto:&#105;&#110;&#102;&#111;&#64;&#105;&#108;&#117;&#110;&#97;&#46;&#99;&#111;&#46;&#106;&#112;">info@iluna.co.jp</a></div>
							  <div id="index_yellow"><strong>所在地</strong></div>
							  <div id="index_contents">〒141-0031</div>
							  <div id="index_contents">東京都品川区西五反田2-24-4 WEST HILL4F</div>
							  <div id="index_yellow"><strong>役員</strong></div>
							  <div id="index_contents">最高経営責任者 矢作 嘉男</div>
							  <div id="index_contents">最高経営執行者 本間 圭一</div>
							  <div id="index_contents">&nbsp;</div>

							</td>
							<td class="bottom_right2">
								<div id="title_right"><img alt="" src="img/1_z6.gif">メッセージ</div>
								<div id="line"><img alt="" src="img/1_line1.gif"></div>
							  <div class="free_comment">
                                株式会社イルナ( iLUNA, Inc. ) は2008年7月設立のベンチャー企業です。
社名の由来はIlluminae(光を当てる)とluna(月)を掛け合わせた造語で、月のようにお客様の
足元を照らす役割をイルナが担えればと考えております。</div>

							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	  </td>
	</tr>
</table>
</body>
</html>









