<table>
	<tr>
		<td class="top1">
			<table>
				<tr>
					<td class="top1_left">
						  <div>www.iluna.co.jp</div>
						  <div><a href="/"><img alt="イルナ" src="img/logo.gif"></a></div>
					</td>
					<td class="top1_right">
						<div class="img">
							<a href="/"><img alt="" src="img/p1.gif"></a><a href="service.html"><img alt="" src="img/p2.gif"></a><a href="about.html"><img alt="" src="img/p3.gif"></a><a href="alliance.html"><img alt="" src="img/p4.gif"></a><a href="contact.html"><img alt="" src="img/p5.gif"></a>
						</div>
						<div id="menu">
							<ul>
							<li id="menu01">{if $selected == "index"}<em><a href="/">HOME</a></em>{else}<a href="/">HOME</a>{/if}</li>
							<li id="menu02">{if $selected == "service"}<em><a href="service.html">サービス</a></em>{else}<a href="service.html">サービス</a>{/if}</li>
							<li id="menu03">{if $selected == "about"}<em><a href="about.html">iLUNAとは</a></em>{else}<a href="about.html">iLUNAとは</a>{/if}</li>
							<li id="menu04">{if $selected == "alliance"}<em><a href="alliance.html">アライアン</a></em>{else}<a href="alliance.html">アライアン</a>{/if}</li>
							<li id="menu05">{if $selected == "contact"}<em><a href="contact.html">お問い合わせ</a></em>{else}<a href="contact.html">お問い合わせ</a>{/if}</li>
							</ul>
						</div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td class="top2">
			<table>
				<tr>
					<td class="bg"></td>
					<td class="top2_left">
			<div id="title_left">
			<img alt="" src="img/1_z1.gif">ニュース
			</div>
			<div id="line"><img alt="" src="img/1_line1.gif"></div>
			{include file="include/top_news.inc"}
<div id="line"><img alt="" src="img/1_line2.gif"></div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>