<table>
	<tr>
		<td class="top1">
			<table>
				<tr>
					<td class="top1_left">
						  <div>www.iluna.co.jp</div>
						  <div><a href="/"><img src="/img/logo.gif" width="221" height="78" alt="株式会社イルナ" /></a></div>
					</td>
					<td class="top1_right">
						<div class="img">
							<a href="/"><img src="/img/p1.gif" width="97" height="66" alt="ホーム" /></a><a href="/service.html"><img src="/img/p2.gif" width="96" height="66" alt="サービス" /></a><a href="/about.html"><img src="/img/p3.gif" width="98" height="66" alt="イルナとは" /></a><a href="/press/2008/"><img src="/img/p4.gif" width="97" height="66" alt="プレスリリース" /></a><a href="/contact.html"><img src="/img/p5.gif" width="97" height="66" alt="お問い合わせ" /></a>
						</div>
						<div id="menu">
							<ul>
							<li id="menu01">{if $selected == "index"}<em><a href="/">HOME</a></em>{else}<a href="/">HOME</a>{/if}</li>
							<li id="menu02">{if $selected == "service"}<em><a href="/service.html">サービス</a></em>{else}<a href="/service.html">サービス</a>{/if}</li>
							<li id="menu03">{if $selected == "about"}<em><a href="/about.html">iLUNAとは</a></em>{else}<a href="/about.html">iLUNAとは</a>{/if}</li>
							<li id="menu04">{if $selected == "press"}<em><a href="/press/2008/">プレスリリース</a></em>{else}<a href="/press/2008/">プレスリリース</a>{/if}</li>
							<li id="menu05">{if $selected == "contact"}<em><a href="/contact.html">お問い合わせ</a></em>{else}<a href="/contact.html">お問い合わせ</a>{/if}</li>
							</ul>
						</div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td class="top2">
			<table>
				<tr>
					<td class="bg"></td>
					<td class="top2_left">
			<div id="title_left">
			<img src="/img/1_z1.gif" width="13" height="13" alt="" />ニュース
			</div>
			<div id="line"><img src="/img/1_line1.gif" width="191" height="1" alt="" /></div>
			{include file="include/top_news.inc"}
<div id="line"><img src="/img/1_line2.gif" width="189" height="1" alt="" /></div>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>