<div class="press">
<dl>
<dt class="title">mixiアプリ『教えてCA! 模擬テスト』開始<br />～キャビンアテンダント志望者の為に航空業界の知識が身につくアプリをmixi内で展開～
</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>Web メディア企画の株式会社イルナ(本社:東京都渋谷区、代表取締役:矢作嘉男)は、キャビンアテンダント志望者が気軽に航空業界の知識を見つけることが出来る『教えてCA! 模擬テスト』をmixi内で開始します。</dd>

<dt class="subtitle">mixiアプリ『教えてCA! 模擬テスト』の概要</dt>
<dd>キャビンアテンダントになるために役立つ模擬テストをmixi内で毎週配信します。キャビンアテンダントを目指す方は勿論のこと、航空関連業務に就きたい方は本アプリを利用することで、気軽に航空業界の知識を身につけることが可能になります。尚、本サービスのアクセスはパソコンからのみ可能で、利用は無料です。</dd>

<dt class="subtitle">『教えてCA! 模擬テスト』へのアクセス方法</dt>
<dd><a href="http://mixi.jp/run_appli.pl?id=19198" target="_blank">http://mixi.jp/run_appli.pl?id=19198</a>（※mixiへの会員登録が必要です）</dd>

<dt class="subtitle">サービス概要</dt>
<dd>
・毎週金曜日に新しい模擬テストが公開されます。<br />
・模擬テストは1テストにつき1回のみ回答可能です。<br />
・1問正解につき10ポイントです。<br />
・早く回答するとボーナスポイントがつきます。<br />
・マイミクランキングも搭載しています。
</dd>

<dt class="subtitle">会社概要・本件に関するお問い合わせ先</dt>
{include file="include/press/corp_yoyogi.inc"}
<dt class="subtitle">本件に関するお問い合わせ先</dt>
<dd>株式会社イルナ 『教えてCA!』運営事務局 担当：矢作{mailto address="info@iluna.co.jp" encode="hex" text="info@iluna.co.jp"}</dd>

</dl>
</div>
