<div class="press">
<dl>
<dt class="title">イルナとマテリアル、各芸能人の注目度や傾向をつかんで<br />オンラインで仕事依頼が出来る『タレントの窓口』を共同運営開始</dt>
{include file="include/press/pdf.inc"}
<dd>報道関係者各位<br />プレスリリース</dd>
<dd class="right">{$date_timestamp|date_format2}<br />株式会社イルナ<br />株式会社マテリアル</dd>
<dd>
Web メディア企画・運営を行う株式会社イルナ(本社:東京都品川区、代表取締役社長:矢作嘉男)とTV PR やタレントキャスティング業務を行う株式会社マテリアル（本社：東京都渋谷区 代表取締役社長：東義和）は共同で、企業がWeb でタレントに出演依頼が出来る『<a href="http://www.talemado.com/">タレントの窓口（http://www.talemado.com/）</a>』をスタートいたします。
</dd>

<dt class="subtitle">『タレントの窓口』サービス詳細</dt>
<dd>
今まで企業や学園祭主催者等が芸能人やタレントにイベント出演や商品PR 依頼を行う場合、各タレントに対してのお問合せ窓口が分かりにくい為、タレントキャスティングは非常に敷居の高い業務でした。<br />
そこでイルナとマテリアルは、キャスティング依頼をしたい企業や学校と芸能人及び芸能事務所をWeb で繋ぐことで、企業がタレントへ仕事依頼することを身近にいたします。<br />
また、企業がタレント選定の目安をつけやすくするために、各タレント名での検索データや各タレントのことを書いているブロガーの年代・性別・居住地などをWeb サイト上に掲載します。これらのデータを参考にすることで、企業側はタレント選定の選択基準の指標を持つことが出来ます。<br />
尚、検索データは<a href="http://www.kwhunter.com/">キーワードハンター（http://www.kwhunter.com/）</a>、ブログデータは<a href="http://blogsphere.biz/">Blogsphere（http://blogsphere.biz/）</a>のデータを活用しています。
</dd>

<dt class="subtitle">『タレントの窓口』の芸能人活用例</dt>
<dd>
・プレスイベント：タレントを起用し、マスコミ誘致によるメディア露出<br />
・地元特産品PR：地元出身タレントを起用した商品PR<br />
・学園祭ゲスト：学園祭に芸能人を呼び集客UP<br />
・結婚式や企業イベント：サプライズゲストとして場を盛り上げる<br />
・商品サンプリング：タレントへの商品サンプリング<br />
・タレントプロデュース商品開発：商品にタレントの冠をつけ注目度を上げる
</dd>

<dt class="subtitle">会社概要</dt>
<dd>
○株式会社イルナ<a href="{$smarty.const.ILUNAURL}/">http://www.iluna.co.jp/</a><br />
〒141-0031 東京都品川区西五反田2-24-4 WEST HILL4F<br />
TEL：03-5436-6508 FAX：03-5436-0860<br /><br />

○株式会社マテリアル<a href="http://materialpower.co.jp/">http://materialpower.co.jp/</a><br />
〒150-0042 東京都渋谷区宇田川町42-3 T&K ビル 3F<br />
TEL：03-5428-6600 FAX：03-5428-6601<br />
</dd>

<dt class="subtitle">本件に関するお問い合わせ先</dt>
<dd>
株式会社マテリアル 担当：東（{mailto address="info@materialpower.co.jp" encode="hex" text="info@materialpower.co.jp"}）
</dd>

</dl>
</div>
