<div class="press">
<dl>
<dt class="title">芸能人にオンラインで仕事依頼が可能な『タレントの窓口』に<br />学園祭・結婚式にも出演依頼が出来る特集ページを追加</dt>
{include file="include/press/pdf.inc"}
<dd>報道関係者各位<br />プレスリリース</dd>
<dd class="right">{$date_timestamp|date_format2}<br />株式会社イルナ<br />株式会社マテリアル</dd>
<dd>
Web メディア企画・運営を行う株式会社イルナ(本社:東京都品川区、代表取締役社長:矢作嘉男)とPR・キャスティング業務を行う株式会社マテリアル（本社：東京都渋谷区 代表取締役社長： 東義和） が共同運営するタレント出演依頼サイト『<a href="http://www.talemado.com/">タレントの窓口</a>』にて、4 月22 日より学園祭・結婚式にも出演依頼が出来る特集ページを追加いたします。
</dd>

<dt class="subtitle">『タレントの窓口』学園祭・結婚式へ出演可能なタレント特集ページ詳細</dt>
<dd>
今まで学園祭の主催者様がタレントに出演依頼をしたい場合、希望タレントへのお問い合わせ窓口が明確化していないためタレントキャスティングは非常に敷居の高い業務でした。<br />
そこで『タレントの窓口』は、学園祭にタレントを呼びたい学園祭主催者様のために、学園祭出演可能タレントの窓口ページを追加いたします。これにより、学園祭主催者様のお問い合わせ相談窓口から実施までを一本化し、学園祭主催者様の負担を軽減いたします。<br /><br />
また、結婚式にタレントをサプライズゲストとしてミニコンサートや司会などに起用出来
るページも併せて追加することで、結婚式でのタレント起用を身近にいたします。
</dd>

<dt class="subtitle">会社概要</dt>
<dd>
○株式会社イルナ<a href="{$smarty.const.ILUNAURL}/">http://www.iluna.co.jp/</a><br />
〒141-0031 東京都品川区西五反田2-24-4 WEST HILL4F<br />
TEL：03-5436-6508 FAX：03-5436-0860<br /><br />

○株式会社マテリアル<a href="http://materialpower.co.jp/">http://materialpower.co.jp/</a><br />
〒150-0042 東京都渋谷区宇田川町42-3 T&K ビル 3F<br />
TEL：03-5428-6600 FAX：03-5428-6601<br />
</dd>

<dt class="subtitle">本件に関するお問い合わせ先</dt>
<dd>
株式会社マテリアル 担当：東（{mailto address="info@materialpower.co.jp" encode="hex" text="info@materialpower.co.jp"}）
</dd>

</dl>
</div>
