<div class="press">
<dl>
<dt class="title">全上場企業の年収チェックサイト『転職のモノサシ』モバイル版を開始<br />～未曾有の経済危機状態での年収動向をモバイルで把握～</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>Web メディア企画の株式会社イルナ(本社:東京都品川区、代表取締役:矢作嘉男)は、上場企業の年収・給料を計るサイト『転職のモノサシ』のモバイル版の運営を開始しました。</dd>

<dt class="subtitle">『転職のモノサシ』モバイルの概要</dt>
<dd>2008年8月にスタートしたパソコン版『転職のモノサシ』は全上場企業の年収に関するデータを様々な観点から比較・シミュレーションしてきました。サイト開始直後に起きたリーマン・ショックの影響もあり、年収動向に敏感になったビジネスマンや学生を中心に利用され、月間で100万ページビューを超えるサイトに成長しました。サイトの成長に伴い、利用者から携帯電話でも年収動向を把握したいというリクエストが多数寄せられていたため、この度モバイル版を開発しました。</dd>

<dt class="subtitle">『転職のモノサシ』モバイルのURL及びQRコード</dt>
<dd>http://m.tenmono.com/<br /><img alt="" src="/img/press/qr_tenmono.jpg" width="90" height="90" /></dd>

<dt class="subtitle">『転職のモノサシ』モバイルの今後</dt>
<dd>
今後イルナでは『転職のモノサシ』モバイルの利便性向上を継続して行い、年収データをASPとして他社モバイルサイトへのコンテンツ提供、及び広告媒体化を進めていく方針です。
</dd>

<dt class="subtitle">会社概要</dt>
{include file="include/press/corp_gotanda2.inc"}
<dt class="subtitle">本件に関するお問い合わせ先</dt>
{include file="include/press/contact.inc"}

</dl>
</div>
