<div class="press">
<dl>
<dt class="title">キャビンアテンダント合格支援サイト『教えてCA!』が<br />元CAによるWeb上での模擬面接とCA志望者同士の掲示板機能を追加</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>『教えてCA!』を運営するWeb メディア企画の株式会社イルナ(本社:東京都品川区、代表取締役:矢作嘉男)は、元CAがWeb上で面接やフライトで起きる事例を元にした模擬面接機能と、CA志望者同士での情報交換が出来る掲示板機能を追加しました。</dd>

<dt class="subtitle">『模擬面接』機能の概要</dt>
<dd>キャビンアテンダントの採用面接時や、実際のフライトでの経験を元にした実践的で受験時に役に立つ課題をWeb上で毎週紹介します。CA志望者は元CAからの課題に対して回答をすると、元CAの助言がWeb上に書き込まれます。模擬面接は毎週行われ、CA志望者は回答を書き込むことでCAになるための考え方や行動を学ぶことが出来ます。</dd>

<dt class="subtitle">『掲示板』機能の概要</dt>
<dd>
CA志望者同士がCAになるために必要な様々な疑問や悩みを、メンバー登録したもの同士で相談をすることが出来ます。メンバーからのCA関連情報が蓄積されることで、CA志望者は受験に対して準備を備えることが出来ます。
</dd>

<dt class="subtitle">模擬面接及び掲示板のURL</dt>
<dd>
<a href="http://www.oshiete-ca.com/bulletin/list">http://www.oshiete-ca.com/bulletin/list</a><br />
今後もイルナでは『教えてCA!』の利便性向上を強化すると共に、モバイル対応・広告媒体化を進めていく方針です。
</dd>

<dt class="subtitle">会社概要</dt>
{include file="include/press/corp_gotanda2.inc"}
<dt class="subtitle">本件に関するお問い合わせ先</dt>
{include file="include/press/contact.inc"}

</dl>
</div>
