<div class="press">
<dl>
<dt class="title">国内最大級の掲載物件数『東京サービスアパートメント』がサイトを大幅刷新<br />高級物件の値引き情報満載。低迷する長期国内出張・旅行ニーズを喚起</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>Webメディア企画の株式会社イルナ(本社:東京都品川区、代表取締役:矢作嘉男)は、『東京サービスアパートメント（http://www.serviced-apartments-tokyo.com/）』の大幅リニューアルを行いました。掲載企業から優先的に提供された高級物件の割引キャンペーン情報を多数掲載することで、都内の高級サービスアパートメント長期滞在ニーズを喚起します。</dd>

<dt class="subtitle">リニューアルのポイント</dt>
<dd>この度のリニューアルでは、リニューアルを記念して掲載企業各社より提供されたキャンペーン情報を数多く掲載しています。キャンペーンの中には当サイトのみの期間限定値引き情報が数多く掲載されています。<br />
また併せて全ページ英語化もすることで、海外からのアクセスにも対応、さらに部屋情報へのアクセスランキングから、どの物件が注目されているかを参考に部屋探しが行えます。</dd>

<dt class="subtitle">『東京サービスアパートメント』の概要</dt>
<dd>
2008年11月に『東京サービスアパートメント』は首都圏のサービスアパートメントをWebでの紹介するサイトとしてスタートしました。現在では、日本のサービスアパートメント紹介サイトとして国内最大級の掲載企業数に成長しました。
</dd>

<dt class="subtitle">『東京サービスアパートメント』のURL</dt>
<dd>
<a href="http://www.serviced-apartments-tokyo.com/">http://www.serviced-apartments-tokyo.com/</a>
</dd>

<dt class="subtitle">会社概要</dt>
{include file="include/press/corp_gotanda2.inc"}
<dt class="subtitle">本件に関するお問い合わせ先</dt>
{include file="include/press/contact.inc"}

</dl>
</div>
