<div class="press">
<dl>
<dt class="title">キャビンアテンダント合格支援サイト『教えてCA!』がモバイル版をスタート<br />～羽田空港ハブ化による客室乗務員の需要増を支援～</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>Webメディア企画の株式会社イルナ(本社:東京都品川区、代表取締役:矢作嘉男)は、『教えてCA!』のモバイル版（http://m.oshiete-ca.com/）を開始しました。国土交通省による羽田の国際ハブ空港化宣言により、高まると見られる客室乗務員の採用増加を支援します。</dd>

<dt class="subtitle">『教えてCA!』について</dt>
<dd>キャビンアテンダント志望者が就職・転職活動でのノウハウや悩みなどに対して、元キャビンアテンダントや、同じ志の志望者が回答をするサイトとして、パソコン版は2009年6月30日に開始しました。他の機能として、公認キャビンアテンダントが面接や実践で役立つWeb模擬面接の配信、最新の採用情報の掲載などキャビンアテンダントになるために必要な情報を無料で得ることが出来ます。</dd>

<dt class="subtitle">モバイル版の概要</dt>
<dd>モバイル版はパソコン版と同様の機能を用意しています。通学・通勤での移動時間や、休み時間などパソコンへのアクセスが難しい時間でも、今後はモバイル版を使って質問や掲示板に書き込むことが可能になります。</dd>

<dt class="subtitle">モバイル版のURLとQRコード</dt>
<dd>URL：http://m.oshiete-ca.com/<br /><img alt="" src="/img/press/qr_ca.jpg" width="91" height="91" /></dd>
<dt class="subtitle">会社概要・本件に関するお問い合わせ先</dt>
{include file="include/press/corp_gotanda2.inc"}
<dt class="subtitle">本件に関するお問い合わせ先</dt>
{include file="include/press/contact.inc"}

</dl>
</div>
