<div class="press">
<dl>
<dt class="title">年収・給料を計るサイト「転職のモノサシ」8月11日スタート。</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>
株式会社イルナ(本社:東京都品川区、代表取締役社長:矢作嘉男)は、上場企業の年収・給料を計るサイト「転職のモノサシ」をオープンしました。<br />
<a href="http://www.tenmono.com/">http://www.tenmono.com/</a>
</dd>

<dt class="subtitle">「上場企業の年収・給料を計るサイト「転職のモノサシ」サービス詳細</dt>
<dd>
転職活動をする際に企業風土や業績などを事前に把握することは勿論ですが、やはり気になるのが年収や給料です。今回イルナがサービスインした「転職のモノサシ」は金融庁のEDINET がもつデータを元に、年収・給料に関するデータを様々な観点から比較・シミュレーションして提供しています。今後はAPI化/コンテンツアグリゲーション/モバイル対応/広告媒体化を進めていく予定です。
</dd>

<dt class="subtitle">主なコンテンツ</dt>
<dd>
各上場企業の年齢別年収シミュレーション・業界年収比較・直近5年の年収推移・業界別年収順位
</dd>

<dt class="subtitle">ブログパーツ詳細</dt>
<dd>
ブログやHP 上で上場企業の年収を検索可能なブログパーツを配布（無料・登録不要）します。また、各種年収データもブログなどで引用しやすいようにHTMLコードを発行していますので、ブロガーは各種データを引用しながらエントリーを作成することが可能です。
</dd>
<dt class="subtitle">問い合わせ・取材依頼</dt>
{include file="include/press/corp_gotanda2.inc"}
{include file="include/press/contact.inc"}

</dl>
</div>
