<div class="press">
<dl>
<dt class="title">イルナ、上場企業約4,000社の年収データを活用できる<br />「転職のモノサシASP」提供開始<br />～SEO用外部リンクコンテンツ、LPO、モバイルコンテンツ等で活用可能～</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>
株式会社イルナ(本社:東京都品川区、代表取締役社長:矢作嘉男)は、同社が運営する企業の年収・給料を計るサイト「転職のモノサシ」の各種年収コンテンツをASPとして外部へ提供するWebサービス『転職のモノサシASP』（<a href="http://www.tenmono.com/asp/">http://www.tenmono.com/asp/</a>）を10月16日より提供開始します。提供先第1社目として、株式会社翔泳社の運営する転職情報サイトCAREERzineが導入し、約7,000ページのコンテンツが「転職のモノサシ ASP」を利用し新たに生成されました。<br />
CAREERzine導入ページ：<a href="http://careerzine.jp/monosashi/search">http://careerzine.jp/monosashi/search</a>
</dd>

<dt class="subtitle">「転職のモノサシ ASP」開発の背景</dt>
<dd>
昨今企業のWEBマーケティングにおいて、サイトコンテンツの開発・更新を継続的に行っていくことは非常に重要ですが、日々の業務に忙殺され開発はおろか更新すら間々ならないという悩みを抱えている企業が多くあります。
そこでイルナでは、全上場企業約4,000社分の年収を切り口とした膨大な情報量と質を担保しつつ、自動でデータ取得・更新可能な『転職のモノサシASP』を月額38,000円という低価格で企業に提供することで、企業のサイトコンテンツの拡充を支援いたします。
</dd>

<dt class="subtitle">「転職のモノサシ ASP」想定対象導入先</dt>
<dd>
※モバイルサイトも対応可能です<br />
・ポータルサイト：コンテンツ拡充によりPVアップさせたい企業<br />
・SEO：外部リンク対策用の衛星サイトとして活用したい企業<br />
・LPO：年収ベースに多くのLPOをトライアルしたい企業<br />
・人材系会社：ユーザを年収査定へ誘導し登録促進したい企業
</dd>

<dt class="subtitle">「転職のモノサシ ASP」サービス詳細</dt>
<dd>
・全上場企業約4,000社分の年収分析、各業界年収分析コンテンツ<br />
・コンテンツ自動更新機能<br />
・月額プラン：38,000円（税別）　年間プラン：364,800円（税別）
</dd>

<dt class="subtitle">主なコンテンツ</dt>
<dd>
各上場企業の基本データに加え、年齢別年収シミュレーション・業界年収比較・直近5年の年収推移・業界別年収順位ダイジェスト
</dd>
<dt class="subtitle">問い合わせ・取材依頼</dt>
{include file="include/press/corp_gotanda2.inc"}
{include file="include/press/contact.inc"}

</dl>
</div>
