<div class="press">
<dl>
<dt class="title">年収・給料を計るサイト「転職のモノサシ」<br />年収が気になる企業ランキング2008を発表</dt>
{include file="include/press/pdf.inc"}
{include file="include/press/sign.inc"}
<dd>
株式会社イルナ(本社:東京都品川区、代表取締役社長:矢作嘉男)は、上場企業の年収・給料を計るサイト「転職のモノサシ」β版公開以来蓄積されたサイト内検索データを用い、 「年収が気になる企業ランキング2008」（期間：2008年7月1日～11月25日　対象：上場企業）を 発表しました。<br />
「年収が気になる企業ランキング2008」URL:<a href="http://www.tenmono.com/rank/">http://www.tenmono.com/rank/</a>
</dd>

<dt class="subtitle">年収検索回数1位はソニー。TOP10のうち9社が製造業という結果に</dt>
<dd>
    <table class="ranking">
    <tr><th>検索順位</th><th>企業名</th><th>実年収順位</th><th>検索順位</th><th>企業名</th><th>実年収順位</th></tr>
    <tr><td>1</td><td>ソニー</td><td>87</td><td>26</td><td>オムロン</td><td>239</td></tr>
    <tr><td>2</td><td>富士通</td><td>231</td><td>27</td><td>トランスコスモス</td><td>3259</td></tr>
    <tr><td>3</td><td>パナソニック</td><td>179</td><td>28</td><td>資生堂</td><td>1367</td></tr>
    <tr><td>4</td><td>東芝</td><td>247</td><td>29</td><td>リコー</td><td>182</td></tr>
    <tr><td>5</td><td>キーエンス</td><td>9</td><td>30</td><td>花王</td><td>272</td></tr>
    <tr><td>6</td><td>ＮＥＣ</td><td>430</td><td>31</td><td>ブリヂストン</td><td>1161</td></tr>
    <tr><td>7</td><td>三菱電機</td><td>299</td><td>32</td><td>凸版印刷</td><td>927</td></tr>
    <tr><td>8</td><td>キヤノン</td><td>163</td><td>33</td><td>ＫＤＤＩ</td><td>138</td></tr>
    <tr><td>9</td><td>電通</td><td>14</td><td>34</td><td>ヤフー</td><td>1635</td></tr>
    <tr><td>10</td><td>デンソー</td><td>172</td><td>35</td><td>楽天</td><td>1585</td></tr>
    <tr><td>11</td><td>三菱商事</td><td>10</td><td>36</td><td>ニコン</td><td>160</td></tr>
    <tr><td>12</td><td>ホンダ</td><td>210</td><td>36</td><td>小松製作所</td><td>235</td></tr>
    <tr><td>13</td><td>京セラ</td><td>1209</td><td>38</td><td>旭硝子</td><td>249</td></tr>
    <tr><td>14</td><td>日立製作所</td><td>425</td><td>39</td><td>住友商事</td><td>7</td></tr>
    <tr><td>15</td><td>三井物産</td><td>12</td><td>40</td><td>村田製作所</td><td>706</td></tr>
    <tr><td>16</td><td>ＮＴＴ</td><td>151</td><td>41</td><td>新日本製鐵</td><td>419</td></tr>
    <tr><td>17</td><td>任天堂</td><td>79</td><td>42</td><td>味の素</td><td>162</td></tr>
    <tr><td>18</td><td>旭化成</td><td>117</td><td>43</td><td>ローム</td><td>496</td></tr>
    <tr><td>19</td><td>シャープ</td><td>365</td><td>44</td><td>アルバック</td><td>475</td></tr>
    <tr><td>20</td><td>トヨタ自動車</td><td>201</td><td>45</td><td>日本郵船</td><td>61</td></tr>
    <tr><td>21</td><td>三菱重工業</td><td>376</td><td>46</td><td>ソフトバンク</td><td>93</td></tr>
    <tr><td>22</td><td>東レ</td><td>997</td><td>47</td><td>富士ソフト</td><td>2066</td></tr>
    <tr><td>23</td><td>大日本印刷</td><td>731</td><td>48</td><td>日本通運</td><td>1542</td></tr>
    <tr><td>24</td><td>東京電力</td><td>314</td><td>49</td><td>野村総合研究所</td><td>30</td></tr>
    <tr><td>25</td><td>オリンパス</td><td>261</td><td>50</td><td>メイテック</td><td>1569</td></tr>
    </table>
</dd>

<dt class="subtitle">レビュー</dt>
<dd>
堂々の1位に輝いたのはソニーでした。圧倒的な知名度から、注目度も常に高い位置をキープしていました。2位は富士通で、こちらも知名度と平均年収の高さではソニーに勝るとも劣らない企業ですが、一歩及ばず2位という結果となっています。社名変更があったパナソニックは3位となりました。
</dd>

<dt class="subtitle">「転職のモノサシ」年収が気になる企業ランキングとは？</dt>
<dd>
このランキングは、上場企業の年収を調べることが出来る「転職のモノサシ」サイト内でユーザにより検索された企業名のデータを用いて統計・発表しているものです。今後も定期的にランキングを発表していきます。年収は世の中の景気や動向に左右されやすいものです。その為、今年収が気になる企業や業種はどこかなのかを知ることで、世の中の転職・雇用の一つの傾向を探る手助けになると思います。
</dd>

<dt class="subtitle">「転職のモノサシ」について</dt>
<dd>
株式会社イルナが運営する「転職のモノサシ」は金融庁EDINET がもつ上場企業データを元に、年収・給料に関するデータを様々な観点から比較・シミュレーションして提供しています。
</dd>
<dt class="subtitle">問い合わせ・取材依頼</dt>
{include file="include/press/corp_gotanda2.inc"}
{include file="include/press/contact.inc"}

</dl>
</div>
